config/routes.rb
Rails.application.routes.draw do

  get "bweets/index"
  post "bweets/create"

  resources :tops
  root 'tops#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout
  get '/search' => 'search#index'

  get '/relationships' => 'relationships#index'

  resources :users do 
    member do
      get :likers, :following, :followers
    end
  end

  resources :relationships, only: [:create]
  resources :follows, only: [:create, :destroy]

  resources :questions do
    resources :answers do
      member do
        get :liking
      end
      resources :comments
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
  	has_many :answers
  # has_many :comments, through: :answers

  	acts_as_taggable

  	validates :title, presence: true, length: { maximum: 30 }
  	validates :description, presence: true, length: { maximum: 140 }
  	validates :theme, presence: true
  	validates :code, presence: true
 end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    if !logged_in?
      flash[:danger] = "ログインしてください。"
      redirect_to '/'
    else
      @question = Question.new
    end
  end

  def create
      @question = Question.new(question_params)
      @user = current_user
      @question.user_id = @user.id

      if @question.save
        redirect_to @question
      else
        render 'new'
      end
  end

  def show
      @question = Question.find(params[:id])
      @user = User.find(@question.user_id)
  end

  def index
    search_word = '%' + params[:question][:title] + '%'
    @questions = Question.find_by_sql(["SELECT * FROM Questions WHERE title LIKE ? or 
                                        description LIKE ? or code LIKE ?", 
                                        search_word, search_word, search_word])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      redirect_to 'edit'
    end
  end

  private

      def question_params
          params.require(:question).permit(:title, :description, :code, :theme, :tag_list, :test)
    end
end

app/views/questions/_like_count.html.erb
<div id="good">いいね！<%= object.like %>件</div>

app/views/questions/_like_form.html.erb
<% unless current_user.liking?(object) %>
<div id="like_form">
    <%= form_for(current_user.relationships.build(liked_id: object.id), remote: true) do |f| %>
    	<div><%= f.hidden_field :liked_id %></div>
    	<%= f.submit "いいね！", class: "btn btn-small btn-primary"%>
    <% end %>
</div>
<% end %>

app/views/questions/edit.html.erb
<%= form_for @question, action: 'update' do |f| %>
      	<%= render 'shared/error_messages', object: f.object %>
      	<div class="col-md-10">
	  		<p class="col-md-6">
				題名	  		
	    		<%= f.text_field :title, class: "form-control col-md-12", rows: "1" %>
	  		</p>
	  		<p class="col-md-6">
	  			テーマ<br>
			    <%= f.radio_button :theme, 'Readable' %> <%= f.label :theme_1, '可読性' %>
			    <%= f.radio_button :theme, 'Speed' %> <%= f.label :theme_2, 'スピード' %>
			    <%= f.radio_button :theme, 'Recylable' %> <%= f.label :theme_3, '再利用性' %>
			    <%= f.radio_button :theme, 'other' %> <%= f.label :theme_4, 'その他' %>
	  		</p>
	  		<p class="col-md-12">
				タグ <br>
				<%= f.text_field :tag_list, class: "form-control col-md-10", rows: "1", 'data-role' => 'tagsinput' %>
			</p>
	  		<p class="col-md-12">
	  			説明
			    <%= f.text_area :description, class: "form-control col-md-10", rows: "3"%>
	  		</p>
	  		<div class="col-md-6">
	  			コード<div id="mark">markdown</div>
				<%= f.text_area :code, class: "form-control", rows:"15" %>
			</div>
			<div class="col-md-6">
				テスト<div id="mark">markdown</div>
				<%= f.text_area :test, class: "form-control", rows:"15" %>
			</div>
	  		<div class="col-md-3">
	    		<%= f.submit :Submit, class: "btn btn-success" %>
	  		</div>
	  	</div>
<% end %>

app/views/questions/index.html.erb
<div class="row">
  <ul class="media-list col-md-8" id='box'>
    <% @questions.each do |question| %>
      <li class="media">
        <div class="pull-left">
          <a href=<%= user_path(question.user_id) %>>
            <%= image_tag(get_user(question.user_id).image_url, size: '68x68', class: 'media-object') %>
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
            <%=link_to question.title, question %>
            <% question.tag_list.each do |tag| %>
              <div id='tag' class="pull-right" style="font-size: 15px; display: block;">
                #<%= tag %>
              </div>
            <% end %>
          </h4>
          <%= simple_format(question.description) %>
          <div class='time pull-right'><%= question.updated_at.to_formatted_s(:without_second) %></div>
        </div>
      </li>
    <hr>
    <% end %>
  </ul>
</div>

app/views/questions/new.html.erb
<%= form_for @question, url: questions_path do |f| %>
      	<%= render 'shared/error_messages', object: f.object %>
      	<div class="col-md-10">
	  		<p class="col-md-6">
				題名	  		
	    		<%= f.text_field :title, class: "form-control col-md-12", rows: "1" %>
	  		</p>
	  		<p class="col-md-6">
	  			テーマ<br>
			    <%= f.radio_button :theme, 'Readable' %> <%= f.label :theme_1, '可読性' %>
			    <%= f.radio_button :theme, 'Speed' %> <%= f.label :theme_2, 'スピード' %>
			    <%= f.radio_button :theme, 'Recylable' %> <%= f.label :theme_3, '再利用性' %>
			    <%= f.radio_button :theme, 'other' %> <%= f.label :theme_4, 'その他' %>
	  		</p>
	  		<p class="col-md-12">
				タグ <br>
				<%= f.text_field :tag_list, class: "form-control col-md-10", rows: "1", 'data-role' => 'tagsinput' %>
			</p>
	  		<p class="col-md-12">
	  			説明
			    <%= f.text_area :description, class: "form-control col-md-10", rows: "3"%>
	  		</p>
	  		<div class="col-md-6">
	  			コード<div id="mark">markdown</div>
				<%= f.text_area :code, class: "form-control", rows:"15" %>
			</div>
			<div class="col-md-6">
				テスト<div id="mark">markdown</div>
				<%= f.text_area :test, class: "form-control", rows:"15" %>
			</div>
	  		<div class="col-md-3">
	    		<%= f.submit :Submit, class: "btn btn-success" %>
	  		</div>
	  	</div>
<% end %>

app/views/questions/show.html.erb
<div class="row">
    <div class="media col-md-12" id="box">
        <a href=<%= user_path(@user) %> class="pull-left">
            <%= image_tag(@user.image_url, size: "100x100", class: "media-object") %>
        </a>
        <div class="media-body">
            <h3 class="media-heading">
                <%= @question.title %> 
                <%= div_for(@question, class: "label label-primary") do %>
                    <%= @question.theme %>
                <% end %>
                <div class="pull-right" id="tag"> 
                    <% @question.tag_list.each do |tag| %>
                        #<%= tag %>
                    <% end %> 
                </div>
            </h3>
            <%= markdown(@question.description).html_safe %><br>
            <div class="col-md-6">
                <h4>コード</h4>
                <%= markdown(@question.code).html_safe %>
            </div>
            <div class="col-md-6" >
                <% unless @question.test == nil %>
                    <h4>テスト</h4>
                    <%= markdown(@question.test).html_safe %>
                <% end %>
            </div>
        </div>
        <div class='time pull-right'><%= @question.updated_at.to_formatted_s(:without_second) %></div>
    </div>

    <% if current_user?(User.find(@question.user.id)) %>
        <%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-info pull-right', id: 'edit-btn' %>
    <% end %>
    <button class="btn btn-success pull-right" id= 'edit-btn'>回答する</button>
</div>

<div class="row">
    <div class="col-md-8">
    <% @question.answers.each do |answer| %>
        <div class="media" id="box">
            <a href=<%= user_path(get_user(answer.user_id)) %> class="pull-left">
            <%= image_tag(get_user(answer.user_id).image_url, size: "50x50", class: "media-object pull-up") %></a>
            <%= markdown(answer.body).html_safe %>
            <%= div_for(answer, class: "media-body") do %>
                <%= render 'like_count', object: answer %>
                <%= render 'like_form', object: answer if logged_in? %> 
            <% end %>
            <div class='time pull-right'><%= answer.updated_at.to_formatted_s(:without_second) %></div>
        </div>
    <% end %>

    <h2>回答フォーム</h2>
    <%= form_for([@question, @question.answers.build]) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
            <p>
                <div id="mark">markdown</div>
                <%= f.text_area :body, class: "form-control", rows: "10" %>
                <%= f.submit class: "btn btn-success", value: '回答' %>
            </p>
        </div>
    <% end %>  
</div>