config/routes.rb
Rails.application.routes.draw do

  get "bweets/index"
  post "bweets/create"

  resources :tops
  root 'tops#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout
  get '/search' => 'search#index'

  get '/relationships' => 'relationships#index'

  resources :users do 
    member do
      get :likers, :following, :followers
    end
  end

  resources :relationships, only: [:create]
  resources :follows, only: [:create, :destroy]

  resources :questions do
    resources :answers do
      member do
        get :liking
      end
      resources :comments
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
	has_many :answers
	has_many :relationships, foreign_key: "liker_id"
	has_many :liked_answers, through: :relationships, source: :liked
  has_many :follows, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :follows, source: :followed
  has_many :reverse_follows, foreign_key: "followed_id",
                             class_name:  "Follow",
                             dependent: :destroy
  has_many :followers, through: :reverse_follows, source: :follower
	
	def self.find_or_create_from_auth_hash(auth_hash)
		provider = auth_hash[:provider]
		uid = auth_hash[:uid]
		nickname = auth_hash[:info][:nickname]
		image_url = auth_hash[:info][:image]

		User.find_or_create_by(provider: provider, uid: uid) do |user|
			user.nickname = nickname
			user.image_url = image_url
		end
	end

	def liking?(answer)
    relationships.find_by(liked_id: answer.id)
  end

  def like!(answer)
    relationships.create!(liked_id: answer.id)
  end

  def following?(other_user)
  	follows.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    follows.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
  	follows.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	helper_method :get_question

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@questions = @user.questions.paginate(page: params[:page], per_page: 5)
		@answers = @user.answers.paginate(page: params[:page], per_page: 5)
	end

	def update
		@user = User.find(params[:id])
		@user.introduction = params[:user][:introduction]
		@user.save
		redirect_to @user
	end

	def following
	  @user = User.find(params[:id])
	  @users = @user.followed_users.paginate(page: params[:page])
		render 'show_follow'
	end

  def followers
	  @user = User.find(params[:id])
	  @users = @user.followers.paginate(page: params[:page])
	  render 'show_follow'
  end

	private

		def get_question(id)
			@question ||= Question.find(id)
		end 

		def user_params
			params.require(:user).permit(:introduciton)
		end

		def ranking(score)
			@user ||= User.all.order(socre).only(5) 
		end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.follows.build(followed_id: @user.id), remote: true, :authenticity_token => true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.follows.find_by(followed_id: @user.id), html: { method: :delete }, remote: true, :authenticity_token => true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user.id, user_path(user.id) %>
  <br>
<% end %>

app/views/users/show.html.erb
<div class="row">
<div class="col-md-2" id="box">
  <%= image_tag(@user.image_url, size: "100x100", class: "img") %>
  <h3><%= @user.nickname %></h4>
  <a href="http://github.com/<%= @user.nickname %>">
  <div class="stats">
    <a href="<%= following_user_path(@user) %>">
      <strong id="following" class="stat">
        <%= @user.followed_users.count %>
      </strong>
      following
    </a>
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      followers
    </a>
  </div>
    <button class="btn btn-success">Github</button>
  </a>
  <div id="score"> score: <%= @user.total %> </div>
</div>
<div class="col-md-2" style="text-align: center;">
  <%= render 'follow_form' if logged_in? %>
</div>
<div class="col-md-8 pull-right">
  <h3>プロフィール</h3>
  <% if current_user?(@user) %>
    <%= form_for(@user, :url => {:action => 'update'}) do |f| %>
      <%= f.text_area :introduction, class: "form-control col-md-8", rows: "6" %>
      <br>
      <%= f.submit '更新', class: "pull-right btn btn-warning" %>
    <% end %>
  <% else %>
  <div class="well">
    <%= simple_format @user.introduction %>
  </div>
  <% end %>
</div>
</div>
<div class="row">
<div class="col-md-6">
  <h2>質問</h2>
  <ul class="media-list" id="box">
    <% @questions.each do |question| %>
      <li class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to question.title, question %>
            <% question.tag_list.each do |tag| %>
              <div id="tag" class="pull-right" style="font-size: 13px; display: block;">
                #<%= tag %>
              </div>
            <% end %>
          </h4>
          <%= simple_format(question.description) %>
          <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-info pull-right' if current_user?(User.find(question.user.id)) %> 
        </div>
      </li>
      <div class='time pull-right'>
        <%= question.updated_at.to_formatted_s(:without_second) %>
      </div>
      <hr>
    <% end %>
  </ul>
</div>
<h2>回答</h2>
<div class="col-md-6">
  <ul class="media-list" id="box">
    <% @answers.each do |answer| %>
      <li class="media">
        <div class="media-heading">
          <h4 style="display: inline;">
            <%= link_to get_question(answer.question_id).title, get_question(answer.question_id) %>
          </h4>
          <div class="pull-right">
            <div style="color: #777; display: inline;">question by</div>
            <a href=<%= user_path(get_question(answer.question_id).user_id) %>>
              <%= image_tag(get_user(get_question(answer.question_id).user_id).image_url, size: '25x25', class: 'media-object flat') %>
            </a>
          </div>
        </div>
        <div class="media-body">
          <%= markdown(answer.body).html_safe %>
        </div>
      </li>
      <div class='time pull-right'>
        <%= answer.updated_at.to_formatted_s(:without_second) %>
      </div>
      <hr>
    <% end %>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="col-md-3">
    <section>
      <%= image_tag(@user.image_url, size: "100x100") %>
      <h1><%= @user.nickname %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <div class="stats">
        <a href="<%= following_user_path(@user) %>">
          <strong id="following" class="stat">
            <%= @user.followed_users.count %>
          </strong>
          following
        </a>
        <a href="<%= followers_user_path(@user) %>">
          <strong id="followers" class="stat">
            <%= @user.followers.count %>
          </strong>
          followers
        </a>
      </div>
    </section>
    <section>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= image_tag(user.image_url, size: "40x40") %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
  <%= will_paginate renderer: BootstrapPagination::Rails %>
    <% if @users.any? %>
      <ul class="media-list" id="box">
        <% @users.each do |user| %>
          <li class="media">
            <div class="pull-left">
              <a href="/users/<%= user.id %>">
                <%= image_tag(user.image_url, size: '68x68', class: 'media-object') %>
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading"><%= user.nickname %></h4>
              <%= simple_format(user.introduction) %>
            </div>
          </li>
          <hr>
        <% end %>        
      </ul>
    <% end %>
    <%= will_paginate renderer: BootstrapPagination::Rails %>
  </div>
</div>